### ISSUE TITLE
Missing Contents.swift file

### ISSUE THREAD

**Issue by joshuageronimo** [PacktPublishing/Mastering-Swift-4-Fourth-Edition#2]
Hey! I can't open any of the playground file. Xcode keeps stating that Contents.swift file is missing.

**Comment by jmunn** [comment]
Same issue... any remedy?

**Comment by techsachinkumar** [comment]
Hi @joshuageronimo & @jmunn 

I had a look at the code files and all of them contain Contents.swift file in them
Please have a look again at the files within the folders and your issue would be solved.

Regards
